### ISSUE TITLE
Delay on input fields makes Log In workflows wonky

### ISSUE THREAD

**Issue by arjansingh** [dollarshaveclub/ember-uni-form#1]
To reproduce:
1. Create a password field and submit button
2. Type in a "password" quickly and then hit "ENTER"

Expected:
Password is submitted.

Actual:
Error is returned because of the delay in enabling the submit action.

Potential Solution:
Eliminate the delay or make it configurable.

**Comment by briangonzalez** [comment]
+1

**Comment by pwfisher** [comment]
I could have sworn I fixed this... but maybe it was just in my head. We discussed using `focusOut` for this and even tested to make sure that `focusOut` happened before `submit` and it did. Aha. I found it, I fixed it here: d9784df
