### ISSUE TITLE
Any plans to remove use of Function prototype extensions?

### ISSUE THREAD

**Issue by marisawallace** [dollarshaveclub/ember-uni-form#3]
The [Ember Guides section on Disabling Prototype Extensions](https://guides.emberjs.com/v2.2.0/configuring-ember/disabling-prototype-extensions/) says:

> Function is extended with methods to annotate functions as computed properties, via the property() method, and as observers, via the observes() or observesBefore() methods. Use of these methods is now discouraged and not covered in recent versions of the Guides.

Since use of the Function prototype extensions are now officially discouraged, are these any plans to remove them from use in the addon? I have the Function prototype extensions disabled in my app, and would prefer not to have to reenable them to use `ember-uni-form`.

The code can be easily converted over via https://github.com/abuiles/ember-watson#ember-watsonconvert-prototype-extensions

**Comment by pwfisher** [comment]
Submit a PR?

**Comment by marisawallace** [comment]
PR submitted! https://github.com/dollarshaveclub/ember-uni-form/pull/4
