### ISSUE TITLE
Underscores behaviour

### ISSUE THREAD

**Issue by petrjanda** [dollarshaveclub/ember-uni-form#7]
Even though the behaviour makes a lot of sense it took me a bit till I figured out that using attributes like `start_date` on the model isn't really gonna work. I know JavaScript convention is camel case, that said I would assume others also use attribute names generated by their backend, which will often contain underscore.

So just for the reference I had to go to the source code here https://github.com/dollarshaveclub/ember-uni-form/blob/master/addon/models/uni-form-field.js#L16-L19 to understand what's going on under the hood - otherwise the form simply ignores the value.

In my case, renaming model attribute to `startDate` fixed the problem with form not binding the value properly. I would just make this more explicit in docs!

**Comment by pwfisher** [comment]
Thanks for the tip, will do.
